### PR TITLE
Update NVIDIA DGX role to match DGX Software Stack for Ubuntu

### PR DESCRIPTION
**Pull request by ajdecon**
## Summary

The [DGX Software Stack for Ubuntu](https://docs.nvidia.com/dgx/dgx-ubuntu-install-guide/index.html) is a supported mechanism to configure an Ubuntu 20.04 system to match NVIDIA DGX OS 5. This PR will update our `nvidia-dgx` role, which is aimed at the same task, to match the procedure laid out in the DGX Software Stack install guide.

Note: Because the DGX Software Stack only supports Ubuntu 20.04, this PR intentionally drops support for Ubuntu 18.04 from this role.

## Tasks

- [x] Update role to match instructions in install guide
- [x] Update documentation

## Test plan

- [x] Run virtual test to validate basic Ansible logic
- [x] Run on DGX-1
- [x] Run on DGX A100

Tests look good on DGX-1 and DGX A100. I don't have a DGX-2 handy to test, though.

### Virtual test

In order to make it easier to test our DGX role, this PR adds two booleans to the configuration:

- `dgx_override_install`: Perform the install even when we don't detect DGX hardware
- `dgx_override_product_type`: Specify a DGX product type for use in testing

```
$ ansible-playbook -i virtual/config/inventory -l virtual-gpu01 -e '{"dgx_override_install": true, "dgx_override_product_type": "DGXA100"}'  playbooks/nvidia-dgx/nvidia-dgx-stack.yml

PLAY [all] *********************************************************************************************************************************************************************************************************************************

TASK [Include NVIDIA DGX role] *************************************************************************************************************************************************************************************************************

TASK [nvidia_dgx_stack : Check for DGX] ****************************************************************************************************************************************************************************************************skipping: [virtual-gpu01]

TASK [nvidia_dgx_stack : Ubuntu tasks for DGX OS 5] ****************************************************************************************************************************************************************************************included: /home/adeconinck/src/github/deepops/roles/nvidia_dgx_stack/tasks/ubuntu.yml for virtual-gpu01

TASK [nvidia_dgx_stack : Check for Ubuntu version] *****************************************************************************************************************************************************************************************skipping: [virtual-gpu01]

TASK [nvidia_dgx_stack : include 20.04 specific variables for DGX OS 5] ********************************************************************************************************************************************************************ok: [virtual-gpu01]

TASK [nvidia_dgx_stack : remove ubuntu nvidia driver ppa if installed] *********************************************************************************************************************************************************************ok: [virtual-gpu01]

TASK [nvidia_dgx_stack : remove packages when using Bright Computing source image] *********************************************************************************************************************************************************ok: [virtual-gpu01] => (item=['cuda-dcgm', 'cuda-driver', 'libumad2sim0', 'libsim-utils', 'ibutils'])

TASK [nvidia_dgx_stack : remove apt mirror when using Bright Computing source image] *******************************************************************************************************************************************************ok: [virtual-gpu01]

TASK [nvidia_dgx_stack : unload drivers when using Bright Computing source image] **********************************************************************************************************************************************************ok: [virtual-gpu01] => (item=ib_srp)
ok: [virtual-gpu01] => (item=ib_iser)
ok: [virtual-gpu01] => (item=rdma_ucm)
ok: [virtual-gpu01] => (item=rpcrdma)
ok: [virtual-gpu01] => (item=rdma_cm)
ok: [virtual-gpu01] => (item=qedr)

TASK [nvidia_dgx_stack : download and extract DGX OS repo files] ***************************************************************************************************************************************************************************ok: [virtual-gpu01]

TASK [nvidia_dgx_stack : update apt cache] *************************************************************************************************************************************************************************************************changed: [virtual-gpu01]

TASK [nvidia_dgx_stack : install DGX-1 packages for DGX OS 5] ******************************************************************************************************************************************************************************skipping: [virtual-gpu01] => (item=[])

TASK [nvidia_dgx_stack : install DGX-2 packages for DGX OS 5] ******************************************************************************************************************************************************************************skipping: [virtual-gpu01] => (item=[])

TASK [nvidia_dgx_stack : install DGXA100 packages for DGX OS 5] ****************************************************************************************************************************************************************************changed: [virtual-gpu01] => (item=['dgx-a100-system-configurations', 'dgx-a100-system-tools', 'dgx-a100-system-tools-extra'])

TASK [nvidia_dgx_stack : Disable unattended upgrades] **************************************************************************************************************************************************************************************ok: [virtual-gpu01]

TASK [nvidia_dgx_stack : Configure CPU governor to performance mode] ***********************************************************************************************************************************************************************ok: [virtual-gpu01]

TASK [nvidia_dgx_stack : Enable serial over lan] *******************************************************************************************************************************************************************************************ok: [virtual-gpu01]

TASK [nvidia_dgx_stack : Enable logrotate policy] ******************************************************************************************************************************************************************************************changed: [virtual-gpu01]

TASK [nvidia_dgx_stack : Install Mellanox OFED] ********************************************************************************************************************************************************************************************changed: [virtual-gpu01] => (item=['mlnx-ofed-all', 'nvidia-mlnx-ofed-misc'])

TASK [nvidia_dgx_stack : Install Docker and NVIDIA container toolkit] **********************************************************************************************************************************************************************changed: [virtual-gpu01] => (item=['docker-ce', 'nvidia-container-toolkit', 'nv-docker-options'])

TASK [nvidia_dgx_stack : Install NVSM] *****************************************************************************************************************************************************************************************************changed: [virtual-gpu01] => (item=['nvsm', 'nvidia-motd'])

TASK [nvidia_dgx_stack : Install optional packages] ****************************************************************************************************************************************************************************************changed: [virtual-gpu01] => (item=['chrpath', 'cifs-utils', 'fping', 'gdisk', 'iperf', 'ipmitool', 'lsscsi', 'net-tools', 'nfs-common', 'quota', 'rasdaemon', 'pm-utils', 'samba-common', 'samba-libs', 'sysstat', 'vlan', 'build-essential', 'automake', 'bison', 'cmake', 'dpatch', 'flex', 'gcc-multilib', 'gdb', 'g++-multilib', 'libelf-dev', 'libltdl-dev', 'linux-tools-generic', 'm4', 'swig'])

TASK [nvidia_dgx_stack : restart docker service just in case...] ***************************************************************************************************************************************************************************changed: [virtual-gpu01]

TASK [nvidia_dgx_stack : redhat family tasks] **********************************************************************************************************************************************************************************************skipping: [virtual-gpu01]

TASK [nvidia_dgx_stack : configure raid array] *********************************************************************************************************************************************************************************************skipping: [virtual-gpu01]

TASK [nvidia_dgx_stack : perform full OS upgrade on Ubuntu] ********************************************************************************************************************************************************************************skipping: [virtual-gpu01]

RUNNING HANDLER [nvidia_dgx_stack : restart docker] ****************************************************************************************************************************************************************************************changed: [virtual-gpu01]

PLAY RECAP *********************************************************************************************************************************************************************************************************************************virtual-gpu01              : ok=19   changed=9    unreachable=0    failed=0    skipped=7    rescued=0    ignored=0

```

### DGX-1 Test

Installed Ubuntu 20.04 on a DGX-1 and executed the Ansible playbook. After execution, ran `nvsm show health` and confirmed the system was healthy:

```
Health Summary
--------------

112 out of 112 checks are healthy
0 out of 112 checks are unhealthy
0 out of 112 checks are unknown
0 out of 112 checks are informational
0 out of 112 checks are disabled
0 out of 112 checks are skipped
Overall system status is healthy


100.0% [=========================================]
Status: healthy
```

### DGX A100 test

Following a run on a test DGX A100, the system is healthy in all respects that this software stack tests.

Running `nvsm show health`, all checks are healthy but one:

```
Health Summary
--------------

182 out of 184 checks are healthy
1 out of 184 checks are unhealthy
0 out of 184 checks are unknown
1 out of 184 checks are informational
0 out of 184 checks are disabled
0 out of 184 checks are skipped
Overall system status is unhealthy
```

But that one check is just due to the CX-6 interfaces being configured inconsistently:

```
Verify Cluster NIC active link technology consistency................ UnHealthy
    All Network port of the adapter should be in single mode (Ethernet or InfiniBand).
    Found Ethernet for link/s PCI0000_8d_00_0
    Found InfiniBand for link/s PCI0000_0c_00_0, PCI0000_12_00_0, PCI0000_4b_00_0, PCI0000_54_00_0, PCI0000_94_00_0, PCI0000_ba_00_0, PCI0000_cc_00_0
```

Which is an artifact of the particular configuration in the lab where we're testing.

### CODE REVIEW

**Comment by dholt** [comment]
Kind of a nit-pick but is it possible to git re-name the files instead of deleting/re-creating so that we can see the diffs?

**Comment by ajdecon** [comment]
Hmm, that's actually what I did, but git doesn't seem to have followed the rename for some reason. I'll fight with git and see if I can get that to show up.

**Comment by ajdecon** [comment]
@dholt : Hmmmm. I restructured the branch slightly to have a commit that just moved the files, and then another commit that made most of the changes. But Github is still rendering it as a delete/add in the main PR view. 🤔 

The diff does show up in the commit view, see: https://github.com/NVIDIA/deepops/pull/1117/commits/9bb1eb5ba2884e06fc417e809f31297f0ab4bfb8

**Comment by dholt** [comment]
it still isn't really a diff, the entire git commit history is gone for the role. assuming you did a `git mv`? I don't know why it would all be missing. unfortunately i haven't had a chance to test it out, which is why it would be a little easier to see the diff

**Comment by yangatgithub** [comment]
Wrong dgx repo path is installed,  it should be "/etc/apt/sources.list.d/dgx.list",  verification failed.

**Pull request closed without merging**
