### PR TITLE
[WIP] Ported monitoring to use `gpu-monitoring-tools`. Fixes #410.

### LINKED ISSUE #410: Monitoring deployment script no longer works
It looks like the files for the coreos helm charts have moved. The deployment script `k8s_deploy_monitoring.sh` now fails with:

```
helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
Error: Looks like "https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/" is not a valid chart repository or cannot be reached: Failed to fetch https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/index.yaml : 403 Forbidden
```

This is highly repeatable and seems to impact all branches/releases.

It looks like behavior just started early this morning.

### PR DESCRIPTION
**Pull request by michael-balint**
WIP - tested on cluster w/ nodeport - not working in virtual w/ loadbalancer+ingress

### CODE REVIEW

**Comment by supertetelman** [comment]
With this change we'll have to update the air-gap support at some point.

**Comment by supertetelman** [comment]
When I deploy this on my AWS Terraformed testbed I get prometheus but not Grafana still.

**Comment by dholt** [comment]
This worked for me using NodePort

Grafana took 10-20 seconds to come up, not much we can do about that. You could add some waits if you want, i.e.

`
kubectl -n monitoring wait --for=condition=Ready -l app=prometheus --timeout=90s pod
kubectl -n monitoring wait --for=condition=Ready -l app=kube-prometheus-grafana --timeout=90s pod
kubectl -n monitoring wait --for=condition=Ready -l app=alertmanager --timeout=90s pod
`

The port for Alertmanager didn't show up at the end, I'm guessing adding the waits above would give it enough time.
`
Grafana: http://192.168.4.129:30200/
Prometheus: http://192.168.4.129:30500/
Alertmanager: http://192.168.4.129:/
`

**Comment by michael-balint** [comment]
Closing in favor of #416

**Pull request closed without merging**
