### PR TITLE
Update default values for helm charts repositories

### PR DESCRIPTION
**Pull request by fredrikand**
New Location For Stable and Incubator Charts
https://helm.sh/blog/new-location-stable-incubator-charts/

Add default value for JupyterHub helm charts
https://jupyterhub.github.io/helm-chart/

### CODE REVIEW

**Comment by supertetelman** [comment]
This looks fine to me.

**Comment by ajdecon** [comment]
@fredrikand : Thank you! 

In order to approve, we do need you to accept the DeepOps CLA as detailed in our [CONTRIBUTING](https://github.com/NVIDIA/deepops/blob/master/CONTRIBUTING.md) doc.

Once you sign this off I can merge.

**Comment by fredrikand** [comment]
> @fredrikand : Thank you!
> 
> In order to approve, we do need you to accept the DeepOps CLA as detailed in our [CONTRIBUTING](https://github.com/NVIDIA/deepops/blob/master/CONTRIBUTING.md) doc.
> 
> Once you sign this off I can merge.

@ajdecon Thanks for pointing this out. Signed my commit now

**Review by ajdecon — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
