### PR TITLE
Use alternate method to copy kubectl binary to control host

### PR DESCRIPTION
**Pull request by dholt**
Fix for https://github.com/NVIDIA/deepops/issues/258

Working for me, but so did the old one :)

### CODE REVIEW

**Comment by dholt** [comment]
@ScottESanDiego can't seem to add you as a reviewer

**Comment by ScottESanDiego** [comment]
> @ScottESanDiego can't seem to add you as a reviewer

I'm seeing a failure with the proposed merge:

```TASK [copy kubectl binary to ansible host] *******************************************************************************************************************************************************
fatal: [gpu01]: FAILED! => changed=false
  cmd: /usr/bin/rsync --delay-updates -F --compress --archive --rsh=/usr/bin/ssh -S none -i /home/ubuntu/scotte-mako-inside.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null --out-format=<<CHANGED>>%i %n%L ubuntu@10.0.12.1:/usr/local/bin/kubectl /home/ubuntu/deepops/config/artifacts/kubectl
  msg: |-
    Warning: Permanently added '10.0.12.1' (ECDSA) to the list of known hosts.
    rsync: link_stat "/usr/local/bin/kubectl" failed: No such file or directory (2)
    rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1668) [Receiver=3.1.2]
    rsync: [Receiver] write error: Broken pipe (32)
  rc: 23
```

Indeed, that binary does not live there since it's not a `kube-master`.

```ubuntu@gpu01:~$ ls /usr/local/bin/kube
kubeadm             kubelet             kubernetes-scripts/
```

**Comment by dholt** [comment]
Give it a try now

**Comment by ScottESanDiego** [comment]
Looks like it works now.

```TASK [copy kubectl binary to ansible host] ***********************************************************************************************************************
changed: [mgmt01]

PLAY [all] *******************************************************************************************************************************************************

TASK [check for kubectl] *****************************************************************************************************************************************
ok: [gpu01 -> localhost]

TASK [modify kubectl permissions] ********************************************************************************************************************************
ok: [gpu01 -> localhost]

TASK [copy kubectl to /usr/local/bin] ****************************************************************************************************************************
fatal: [gpu01 -> localhost]: FAILED! => changed=false
  checksum: e9b5ff2f86ecfbadb326493220ed26ac7b95fc88
  msg: Destination /usr/local/bin not writable
...ignoring

TASK [check for copied kubectl] **********************************************************************************************************************************
ok: [gpu01 -> localhost]

TASK [modify kubectl permissions] ********************************************************************************************************************************
skipping: [gpu01]

TASK [manually move kubectl binary] ******************************************************************************************************************************
ok: [gpu01 -> localhost] =>
  msg: 'Unable to move kubectl, run: sudo cp /home/ubuntu/deepops/config/artifacts/kubectl /usr/local/bin'
```

**Comment by supertetelman** [comment]
Works for me too.

**Pull request merged**
