### PR TITLE
Update container registry playbook to work with Helm 3

### PR DESCRIPTION
**Pull request by ajdecon**
Addresses #738 .

- [x] Update container-registry role to work with helm 3
- [x] Configure to use NodePort by default (don't assume a load balancer)
- [x] Add Jenkins test

## Test plan

- [x] Turn up a new k8s cluster with DeepOps
- [x] Install a container registry with the playbook: `ansible-playbook playbooks/k8s-cluster/container-registry.yml`
- [x] Successfully push to cluster registry
- [x] Successfully deploy pod from cluster registry

Started a new virtual k8s cluster with DeepOps. Importantly, this cluster included this new configuration to ensure the local registry can be used without TLS:

```
# Configure so that the in-cluster registry can be accessed without HTTPS
docker_insecure_registries: ["registry.local:31500"]
```

After turning up the virtual cluster, ran the `container-registry.yml` playbook to set up a registry inside the k8s cluster:

```
$ ansible-playbook -i virtual/config/inventory playbooks/k8s-cluster/container-registry.yml
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

PLAY [kube-master] ******************************************************************************************

TASK [Install helm chart for container registry] ************************************************************

TASK [container-registry : install stable helm repository] **************************************************
changed: [virtual-mgmt01]

TASK [container-registry : update helm repos] ***************************************************************
changed: [virtual-mgmt01]

TASK [container-registry : copy values.yaml into place] *****************************************************
ok: [virtual-mgmt01]

TASK [install container-registry] ***************************************************************************
changed: [virtual-mgmt01]

PLAY [kube-node] ********************************************************************************************

TASK [Set registry hostname in /etc/hosts] ******************************************************************
ok: [virtual-mgmt01]
ok: [virtual-gpu01]

PLAY RECAP **************************************************************************************************
virtual-gpu01              : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
virtual-mgmt01             : ok=5    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

I then verify that the `docker-registry` release shows up in `helm list`:

```
$ helm list | grep registry
docker-registry         default         1               2020-10-27 20:20:38.608153767 +0000 UTC deployed    docker-registry-1.9.4            2.7.1
```

And that, after a couple of minutes, the pod has been created and is exposed with a NodePort:

```
$ kubectl get pods | grep registry
docker-registry-c95cb4fdc-h2slm             1/1     Running   0          2m9s
$ kubectl get services | grep registry
docker-registry                      NodePort       10.233.47.166   <none>        5000:31500/TCP
  2m55s
```

I set my local Docker configuration in `/etc/docker/daemon.json` so that the new registry is available without TLS:

```
$ cat /etc/docker/daemon.json
{
        "insecure-registries": ["10.0.0.2:31500"]
}
```

Then, after restarting my local Docker, I pull the `nginx` container and push it to the cluster registry:

```
$ sudo systemctl restart docker

$ docker pull nginx
Using default tag: latest
latest: Pulling from library/nginx
Digest: sha256:ed7f815851b5299f616220a63edac69a4cc200e7f536a56e421988da82e44ed8
Status: Image is up to date for nginx:latest
docker.io/library/nginx:latest

$ docker tag nginx 10.0.0.2:31500/nginx

$ docker push 10.0.0.2:31500/nginx
The push refers to repository [10.0.0.2:31500/nginx]
cdd1d8ebeb06: Pushed
fe08d9d9f185: Pushed
280ddd108a0a: Pushed
f14cffae5c1a: Pushed
d0fe97fa8b8c: Pushed
latest: digest: sha256:4949aa7259aa6f827450207db5ad94cabaa9248277c6d736d5e1975d200c7e43 size: 1362
```

I can manually verify that the image has been pushed using the registry API:

```
$ curl http://10.0.0.2:31500/v2/nginx/tags/list
{"name":"nginx","tags":["latest"]}
```

And then create a pod on the cluster based on this image, using the `registry.local` name:

```
$ cat /tmp/nginx-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: example-from-registry
spec:
  containers:
  - name: nginx
    image: registry.local:31500/nginx
  hostNetwork: true
  dnsPolicy: Default

$ kubectl apply -f /tmp/nginx-pod.yaml
pod/example-from-registry created

$ kubectl get pods | grep example
example-from-registry                       1/1     Running   0          17s

$ kubectl describe pod example-from-registry | grep Image:
    Image:          registry.local:31500/nginx
```

### CODE REVIEW

**Comment by ajdecon** [comment]
Still needs a Jenkins test but otherwise seems to be working.

**Comment by avolkov1** [comment]
https://github.com/NVIDIA/deepops/blob/24ea3f78f236211d271dcb8d7ebe51eba9535cef/roles/container-registry/templates/values.yaml#L1-L4

If you're updating the container registry playbook, could you enable ability to delete local containers as well.

Based on: https://github.com/helm/charts/tree/master/stable/docker-registry#configuration
Something like:
```
persistence:
  enabled: "{{ container_registry_persistence_enabled }}"
  {% if container_registry_persistence_enabled %}size: "{{ container_registry_storage_size }}"{% endif %}
  deleteEnabled: true
```
Or in: `deepops/roles/container-registry/defaults/main.yml`
```
container_registry_delete_enabled: true
```
Then in `values.yaml`
```
persistence:
  enabled: "{{ container_registry_persistence_enabled }}"
  {% if container_registry_persistence_enabled %}size: "{{ container_registry_storage_size }}"{% endif %}
  deleteEnabled: "{{ container_registry_delete_enabled }}"
```

**Comment by ajdecon** [comment]
@avolkov1 : Seems like a good idea! Added.

**Comment by ajdecon** [comment]
Added container registry to k8s virtual cluster turnup and wrote a Jenkins test. Verified Jenkins test works :) so this should be good to review.

From most recent Jenkins test: 

```
+ bash -x ./workloads/jenkins/scripts/test-local-registry.sh

+ source workloads/jenkins/scripts/jenkins-common.sh

++ pwd

/var/lib/jenkins/workspace/deepops_PR-739

++ '[' -z x ']'

++ export DEEPOPS_FULL_INSTALL=

++ DEEPOPS_FULL_INSTALL=

+++ echo 0-0x02

+++ cut -d, -f1

+++ cut -d- -f1

++ GPU01=0

++ export GPU01

+++ echo 0-0x02

+++ cut -d, -f1

+++ cut -d- -f2

++ BUS01=0x02

++ export BUS01

++ '[' ']'

++++ dirname workloads/jenkins/scripts/jenkins-common.sh

+++ cd workloads/jenkins/scripts

+++ pwd

++ export VIRT_DIR=/var/lib/jenkins/workspace/deepops_PR-739/workloads/jenkins/scripts/../../../virtual

++ VIRT_DIR=/var/lib/jenkins/workspace/deepops_PR-739/workloads/jenkins/scripts/../../../virtual

++ export ROOT_DIR=/var/lib/jenkins/workspace/deepops_PR-739/workloads/jenkins/scripts/../../../virtual/..

++ ROOT_DIR=/var/lib/jenkins/workspace/deepops_PR-739/workloads/jenkins/scripts/../../../virtual/..

++ K8S_CONFIG_DIR=/var/lib/jenkins/workspace/deepops_PR-739/workloads/jenkins/scripts/../../../virtual/config

++ export KUBECONFIG=/var/lib/jenkins/workspace/deepops_PR-739/workloads/jenkins/scripts/../../../virtual/config/artifacts/admin.conf

++ KUBECONFIG=/var/lib/jenkins/workspace/deepops_PR-739/workloads/jenkins/scripts/../../../virtual/config/artifacts/admin.conf

++ export PATH=/var/lib/jenkins/workspace/deepops_PR-739/workloads/jenkins/scripts/../../../virtual/config/artifacts:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin

++ PATH=/var/lib/jenkins/workspace/deepops_PR-739/workloads/jenkins/scripts/../../../virtual/config/artifacts:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin

++ export JENKINS=1

++ JENKINS=1

+ set -ex

+ cd /var/lib/jenkins/workspace/deepops_PR-739/workloads/jenkins/scripts/../../../virtual/..

+ kubectl wait --for=condition=ready --timeout=600s pod -l app=docker-registry

pod/docker-registry-6677fc8d85-mrkc8 condition met

+ scp -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile /dev/null' -i /var/lib/jenkins/.ssh/id_rsa workloads/jenkins/scripts/remote-script-for-registry-test.sh vagrant@10.0.0.20:remote-script-for-registry-test.sh

Warning: Permanently added '10.0.0.20' (ECDSA) to the list of known hosts.

+ ssh -o 'StrictHostKeyChecking no' -o 'UserKnownHostsFile /dev/null' -l vagrant -i /var/lib/jenkins/.ssh/id_rsa 10.0.0.20 'bash -l /home/vagrant/remote-script-for-registry-test.sh'

Warning: Permanently added '10.0.0.20' (ECDSA) to the list of known hosts.

+ sudo docker pull nginx:latest

latest: Pulling from library/nginx

Digest: sha256:ed7f815851b5299f616220a63edac69a4cc200e7f536a56e421988da82e44ed8

Status: Downloaded newer image for nginx:latest

docker.io/library/nginx:latest

+ sudo docker tag nginx registry.local:31500/nginx

+ sudo docker push registry.local:31500/nginx

The push refers to repository [registry.local:31500/nginx]

cdd1d8ebeb06: Preparing

fe08d9d9f185: Preparing

280ddd108a0a: Preparing

f14cffae5c1a: Preparing

d0fe97fa8b8c: Preparing

280ddd108a0a: Pushed

fe08d9d9f185: Pushed

cdd1d8ebeb06: Pushed

f14cffae5c1a: Pushed

d0fe97fa8b8c: Pushed

latest: digest: sha256:4949aa7259aa6f827450207db5ad94cabaa9248277c6d736d5e1975d200c7e43 size: 1362

+ kubectl apply -f workloads/jenkins/scripts/files/nginx-from-local-registry.yml

pod/nginx-registry-local created

+ kubectl wait --for=condition=ready --timeout=300s pod/nginx-registry-local

pod/nginx-registry-local condition met
```

**Review by michael-balint — APPROVED** [review]

**Pull request merged**
