### PR TITLE
Add option to create Rook cluster with an object storage gateway

### PR DESCRIPTION
**Pull request by ajdecon**
I wanted to do some testing with an S3-compatible object store, so I thought I'd do it in DeepOps! This PR adds the option to build a Rook Ceph cluster with the object storage gateway enabled.

Note: In order to make this an option, rather than just change the defaults, I added an environment variable `ROOK_SERVICE_FILE` to `k8s_deploy_rook.sh` to configure which Rook service file should be used to create the cluster.  

I want this optionality for future extension: our current Rook service file is pretty minimal, but users may want to build clusters with replication, erasure coding, or other configuration changes. This was we can maintain our very minimal configuration for virtual and other small-cluster testing, but let users define their more extensive rook cluster without editing DeepOps-provided files.

## To use

To create a new minimal Rook cluster with an object storage gateway:

1. Specify the rook service definition which includes object storage by setting the `ROOK_SERVICE_FILE` environment variable:

    ```
    $ export ROOK_SERVICE_FILE="${DEEPOPS_REPO}/services/rook/rook-minimal-with-object-storage.yml"
    ```

    where `${DEEPOPS_REPO}` is the path to the root of the DeepOps repository.
1. If you're using the virtual cluster to test, turn up your new virtual cluster using ` virtual/cluster_up.sh` script.
1. If you're not using the virtual cluster, turn up your Kubernetes cluster and then run `scripts/k8s_deploy_rook.sh`
1. Wait for the Rook cluster to come fully online.

## Test plan

1. Created a new virtual cluster using the new service definition as above. 
1. After the Rook cluster was online, created a new `ObjectBucketClaim` to create an object bucket in the Ceph cluster:
    ```
    $ kubectl create -f ./services/rook/example-rook-objectstore-bucket.yml
    objectbucketclaim.objectbucket.io/my-bucket-claim created
    ```
1. From your provisioning host, use `kubectl` to get the name of the bucket host, the access key, and the secret key. (Keys are obscured in the text below.)
    ```
    $ # Get the BUCKET_HOST
    $ kubectl -n default get cm my-bucket-claim -o yaml | grep BUCKET_HOST | awk '{print $2}'
    rook-ceph-rgw-objectstore.rook-ceph
    $ # Get the AWS_ACCESS_KEY_ID
    $ echo $(kubectl -n default get secret my-bucket-claim -o yaml | grep AWS_ACCESS_KEY_ID | awk '{print $2}' | base64 --decode)
    <access-key>
    $ # Get the AWS_SECRET_ACCESS_KEY
    $ echo $(kubectl -n default get secret my-bucket-claim -o yaml | grep AWS_SECRET_ACCESS_KEY | awk '{print $2}' | base64 --decode)
    <secret-key>
    ```
1. Get a shell in the `rook-ceph-tools` pod:
    ```
    $ kubectl -n rook-ceph get pods |grep tools
    rook-ceph-tools-856c5bc6b4-qhwsm                1/1     Running     0          16m
    $ kubectl -n rook-ceph exec -it rook-ceph-tools-856c5bc6b4-qhwsm bash
    ```
1. Add the bucket host and keys from above to the local environment in the pod:
    ```
    [root@virtual-gpu01 /]# export BUCKET_HOST=rook-ceph-rgw-objectstore.rook-ceph
    [root@virtual-gpu01 /]# export AWS_ACCESS_KEY_ID=<access-key>
    [root@virtual-gpu01 /]# export AWS_SECRET_ACCESS_KEY=<secret-key>
    ```
1. Install the `s3cmd` utility:
    ```
    [root@virtual-gpu01 /]# yum -y install s3cmd
    ```
1. Create and upload an object. Note the intentional space after the `--host-bucket= ` flag.
    ```
    [root@virtual-gpu01 /]# echo "hello there" > /tmp/rookObj
    [root@virtual-gpu01 /]# s3cmd ls --no-ssl --host=${BUCKET_HOST}
    2020-08-12 19:17  s3://my-bucket-8c3e4709-a8c9-4df4-a83d-987407f1581b
    [root@virtual-gpu01 /]# s3cmd put /tmp/rookObj --no-ssl --host=${BUCKET_HOST} --host-bucket= s3://my-bucket-8c3e4709-a8c9-4df4-a83d-987407f1581b
    upload: '/tmp/rookObj' -> 's3://my-bucket-8c3e4709-a8c9-4df4-a83d-987407f1581b/rookObj'  [1 of 1]
     12 of 12   100% in    0s   101.04 B/s  done
    ```
1. Download that object again and verify its contents.
    ```
    [root@virtual-gpu01 /]# s3cmd get s3://my-bucket-8c3e4709-a8c9-4df4-a83d-987407f1581b/rookObj /tmp/rookObj-download --no-ssl --host=${BUCKET_HOST} --host-bucket=
    download: 's3://my-bucket-8c3e4709-a8c9-4df4-a83d-987407f1581b/rookObj' -> '/tmp/rookObj-download'  [1 of 1]
     12 of 12   100% in    0s   266.00 B/s  done
    [root@virtual-gpu01 /]# cat /tmp/rookObj-download
    hello there
    ```

### CODE REVIEW

**Comment by ajdecon** [comment]
@supertetelman : Good idea! I feel like the README option should go with a larger docs refactor for the scripts directory, so a bit out of scope for this PR. I'll add comments to the script and to the service file instead.

**Comment by supertetelman** [comment]
Some of the changes in https://github.com/NVIDIA/deepops/pull/526 may have impacted this PR, but the conflicts should be minimal.

**Comment by ajdecon** [comment]
@michael-balint : This PR should be ready to review again

**Comment by ajdecon** [comment]
Re-tested this process and updated the test plan with better information.

**Pull request closed without merging**
