### PR TITLE
[enroot] Add role to install from PPA

### PR DESCRIPTION
**Pull request by lukeyeager**
Notes:
* This PPA currently only supports Bionic - not Xenial (see https://github.com/NVIDIA/enroot/pull/4)
* No support for centos yet
* No support for airgapped systems yet

/cc @3XX0

### CODE REVIEW

**Comment by dholt** [comment]
why no centos?

**Comment by 3XX0** [comment]
For RHEL, you also need to tune some [kernel settings](https://github.com/NVIDIA/enroot/blob/master/doc/requirements.md) which require a reboot/kexec.  
Not sure how you do that with ansible.

**Comment by dholt** [comment]
We set kernel cmd line params and reboot in other places with Ansible. I'm ok with leaving it out for now as long as we generate a to-do item for making this work for RHEL/CentOS

**Comment by lukeyeager** [comment]
Will reopen later when I get it working for centos, too.

**Pull request closed without merging**
