### PR TITLE
Grafana: redesigned dashboards, added System Power Draw reporting for DGX-A100

### PR DESCRIPTION
**Pull request by itzsimpl**
I updated the slurm-exporter to the latest version (https://github.com/vpenso/prometheus-slurm-exporter) which can provide also information about the GPUs (the docker image is build on the fly). Note, that unfortunately this may not work with newer versions of slurm (see https://github.com/vpenso/prometheus-slurm-exporter/issues/38). I also slightly redesigned the Grafana SLURM and GPU node dashboards. And I have found a solution for System Power Draw reporting to solve #744. It is based on ipmi-exporter (https://github.com/soundcloud/ipmi_exporter) (the docker image is build on the fly).

### CODE REVIEW

**Comment by dholt** [comment]
Thanks for the PR!

I've seen substantial hangs using an IPMI exporter before, have you tried this over a few weeks on more than a single node?

**Comment by itzsimpl** [comment]
I've been using this IPMI exporter for about 6 months. It is just on a tiny 3 node SLURM setup with one login node, one DGX-A100, and one Intel based system with 4 GPUs. However, until now I have not experienced any hangs.

**Comment by dholt** [comment]
Did you intend to include the Enroot-specific prolog/epilog bits? If not, do you mind moving those to their own PR?

**Comment by itzsimpl** [comment]
I apologise; these were not intended to be included. Frankly speaking I'm unsure how they got included in the first place; they are all from my previous (separate) PRs, which have already been merged into the main branch (and possibly modified afterwards). Any pointers on how to remove them from the PR? Will deleting them using GitHub UI remove the files from the entire repo, or just mark as unchanged with respect to the main repo?

**Comment by itzsimpl** [comment]
I've reverted the unintended commits.

**Comment by itzsimpl** [comment]
Is there anything else that needs to be corrected?

**Comment by dholt** [comment]
I still have a couple concerns, 1) that this won't work with the default newer version of Slurm in DeepOps, and 2) not all nodes have IPMI, does this still work on non-ipmi machines? Unfortunately I haven't had time to test this one yet

**Comment by supertetelman** [comment]
In the future, we should look at integrating these dashboards into the official DCGM repo here: https://github.com/NVIDIA/dcgm-exporter/tree/main/grafana

But, for now it looks like it will be easier for us to just keep it separate.

**Pull request closed without merging**
