### PR TITLE
Add proxy config to standalone container registry

### PR DESCRIPTION
**Pull request by nuka137**
Current standalone container registry can not work on the proxy environment.
This PR enables us to specify the proxy configurations for standalone container registry.

### CODE REVIEW

**Comment by ajdecon** [comment]
@nuka137 : This looks reasonable to me!

Can you please sign off on your commit as detailed in our [CONTRIBUTING.md](https://github.com/NVIDIA/deepops/blob/master/CONTRIBUTING.md) doc? And then I can merge the PR.

**Comment by nuka137** [comment]
@ajdecon 

Recommitted about previous patch.
Could you check it?

**Review by ajdecon — APPROVED** [review]

**Review by ajdecon — CHANGES_REQUESTED** [review]
This actually appears to fail in the default case (without a proxy). If the variable isn't defined, Ansible won't run.

We use a different pattern in other tasks ([example](https://github.com/NVIDIA/deepops/blob/708e61d71a2bd2076eaf48661208cb479a50bc6f/roles/facts/tasks/main.yml#L5)) that looks like this:

```
- name: apt install pciutils
  apt: name=pciutils update_cache=yes
  when: ansible_os_family == 'Debian'
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
```

And then define `proxy_env` if needed:

```
# proxy_env:
      # http_proxy: '{{ http_proxy }}'
      # https_proxy: '{{ https_proxy }}'
      # no_proxy: '{{ no_proxy }}'
```

Can you convert this to either use the same `proxy_env` variable, or a similar pattern that works when no proxy is present?

**Comment by nuka137** [comment]
@ajdecon 

Thanks. I fixed it.

**Review by ajdecon — APPROVED** [review]
LGTM

**Pull request merged**
